 create table Auditorium (id integer generated by default as identity, name varchar(255), numberOfSeats integer not null, numberOfVipSeats varchar(255), primary key (id));
 create table Event (id integer generated by default as identity, date timestamp, msrp double not null, name varchar(255), rating varchar(255), auditorium_id integer, primary key (id));
 create table Event_availableSeats (Event_id integer not null, availableSeats integer);
 create table Event_ticketsSold (Event_id integer not null, ticket_id integer not null);
 create table Ticket (id integer generated by default as identity, price double not null, seatNumber integer not null, event_id integer, user_id integer, primary key (id));
 create table User (id integer generated by default as identity, birthday date, email varchar(255), login varchar(255), name varchar(255), password varchar(255), role varchar(255), primary key (id));
 create table Counter(id integer generated by default as identity,name varchar(255),additionalInfo varchar(255),value integer, primary key (id));